import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

live_config_reload = true

[env]
TERM = "screen-256color"

[font]
size = 10

[font.normal]
family = "JetBrains Mono NF"
style = "Semibold"

[window]
opacity = 0.9

[window.padding]
x = 10
y = 10
