import = [
  "~/.config/alacritty/tokyonight-moon.toml"
]

live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size = 10

[font.normal]
family = "JetBrains Mono NF"
style = "Semibold"

[window]
opacity = 0.95

[window.padding]
x = 5
y = 5
